//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CircleDock.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CircleDock.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hide.
        /// </summary>
        public static string MainWindow_ContextMenu_Hide {
            get {
                return ResourceManager.GetString("MainWindow_ContextMenu_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Quit.
        /// </summary>
        public static string MainWindow_ContextMenu_Quit {
            get {
                return ResourceManager.GetString("MainWindow_ContextMenu_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string MainWindow_ContextMenu_Settings {
            get {
                return ResourceManager.GetString("MainWindow_ContextMenu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings window.
        /// </summary>
        public static string SettingsWindow {
            get {
                return ResourceManager.GetString("SettingsWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Background.
        /// </summary>
        public static string SettingsWindow_Background {
            get {
                return ResourceManager.GetString("SettingsWindow_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CircleInterval.
        /// </summary>
        public static string SettingsWindow_CircleInterval {
            get {
                return ResourceManager.GetString("SettingsWindow_CircleInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Color.
        /// </summary>
        public static string SettingsWindow_Color {
            get {
                return ResourceManager.GetString("SettingsWindow_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Diameter.
        /// </summary>
        public static string SettingsWindow_Diameter {
            get {
                return ResourceManager.GetString("SettingsWindow_Diameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enable rotation.
        /// </summary>
        public static string SettingsWindow_EnableRotation {
            get {
                return ResourceManager.GetString("SettingsWindow_EnableRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Folder image.
        /// </summary>
        public static string SettingsWindow_FolderImage {
            get {
                return ResourceManager.GetString("SettingsWindow_FolderImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Height.
        /// </summary>
        public static string SettingsWindow_Height {
            get {
                return ResourceManager.GetString("SettingsWindow_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hide after open.
        /// </summary>
        public static string SettingsWindow_HideAfterOpen {
            get {
                return ResourceManager.GetString("SettingsWindow_HideAfterOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Icons per circle.
        /// </summary>
        public static string SettingsWindow_IconsPerCircle {
            get {
                return ResourceManager.GetString("SettingsWindow_IconsPerCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Image.
        /// </summary>
        public static string SettingsWindow_Image {
            get {
                return ResourceManager.GetString("SettingsWindow_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language.
        /// </summary>
        public static string SettingsWindow_Language {
            get {
                return ResourceManager.GetString("SettingsWindow_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minimum radius.
        /// </summary>
        public static string SettingsWindow_MinimumRadius {
            get {
                return ResourceManager.GetString("SettingsWindow_MinimumRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Opacity.
        /// </summary>
        public static string SettingsWindow_Opacity {
            get {
                return ResourceManager.GetString("SettingsWindow_Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rotation step.
        /// </summary>
        public static string SettingsWindow_RotationStep {
            get {
                return ResourceManager.GetString("SettingsWindow_RotationStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string SettingsWindow_Save {
            get {
                return ResourceManager.GetString("SettingsWindow_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show Windows context menu.
        /// </summary>
        public static string SettingsWindow_ShowWindowContextMenu {
            get {
                return ResourceManager.GetString("SettingsWindow_ShowWindowContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Button.
        /// </summary>
        public static string SettingsWindow_TabItem_Button {
            get {
                return ResourceManager.GetString("SettingsWindow_TabItem_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dock.
        /// </summary>
        public static string SettingsWindow_TabItem_Dock {
            get {
                return ResourceManager.GetString("SettingsWindow_TabItem_Dock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ring.
        /// </summary>
        public static string SettingsWindow_TabItem_Ring {
            get {
                return ResourceManager.GetString("SettingsWindow_TabItem_Ring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shortcut.
        /// </summary>
        public static string SettingsWindow_TabItem_Shortcut {
            get {
                return ResourceManager.GetString("SettingsWindow_TabItem_Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Window.
        /// </summary>
        public static string SettingsWindow_TabItem_Window {
            get {
                return ResourceManager.GetString("SettingsWindow_TabItem_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Thickness.
        /// </summary>
        public static string SettingsWindow_Thickness {
            get {
                return ResourceManager.GetString("SettingsWindow_Thickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Topmost.
        /// </summary>
        public static string SettingsWindow_Topmost {
            get {
                return ResourceManager.GetString("SettingsWindow_Topmost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Width.
        /// </summary>
        public static string SettingsWindow_Width {
            get {
                return ResourceManager.GetString("SettingsWindow_Width", resourceCulture);
            }
        }
    }
}
